フォントサイズをスライダーで変更できるようコンポーネントを追加
Shiba-github/varia-ui pull request #59
Opened 2022-07-24 15:03 UTC by Actlam

フォントサイズをいじれるようFontSizeコンポーネントを作成

設定値はとりあえずpxで指定
相対値指定やグローバル値での指定は今後必要があれば追加要素として実装はあり

2022-08-04 16:43 UTC, Shiba-github requested changes

2022-08-04 16:43 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
@Actlam 
カスタムエリアで表示した時だけ、コードに表示させる処理を追加してほしい

2022-08-21 14:41 UTC, Actlam commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
これでどうでしょうか
b5fb099c9b5a773c85b1e4a4a6c577ad8e7ce2d0

2022-08-21 15:10 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
on off追加はよさそう

あとrebaseして、copy button押したときにコピーされる処理も追加お願いします

2022-08-21 15:12 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
rebaseについてなんだけど、基本的にはcommit(push)前に、最新のmainに変更があればrebaseするっていうルールでやりたいんだけどどうかな？

その影響で一つのブランチがあまりに膨らんでしまうのであればちょっと考え物だけど…
どやろ？

2022-08-21 15:21 UTC, Shiba-github requested changes
rebase and copy buttonへの追加おねがいしまうま

2022-08-21 15:22 UTC, Actlam commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
mainの最新版をrebaseで取り込むってこと？
こういうときmergeするやりかたしかやったことないからよくわからないんよな

2022-08-21 15:24 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
merge でも全然OK
ただ、そのmergeを実行するときに、HEADがlocalの古いやつを指している場合があるので
mainを最新にするのを忘れなければだいじょぶ

2022-08-21 15:27 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
rebaseとmergeの違う点は、rebaseのほうがgitのlogを見たときにちょっときれい
くらいの違い

2022-08-21 15:28 UTC, Actlam commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
> rebaseについてなんだけど、基本的にはcommit(push)前に、最新のmainに変更があればrebaseするっていうルールでやりたいんだけどどうかな？

これ同意なんだけどmainの変更に気づかずpushしてしまいがち・・・

2022-08-21 15:30 UTC, Actlam commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
あ、でもそのやり方で全く問題ないと思う

2022-08-21 15:30 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
問答無用でmain更新の癖をつけるか、git logでmainとorigin/mainが違う位置にいないか確認するしかないわな

2022-08-21 15:31 UTC, Actlam commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
これに関してはmergeするときに
```sh
git merge origin main
```
すれば解決しそう

2022-08-21 15:31 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
fetch忘れて💩漏らしそう

2022-08-21 15:32 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
まぁ、忘れちゃったら、わすれてるよーって言えばいいし
わすれんようにがんばるくらいの気持ちで✋

2022-08-21 15:32 UTC, Actlam commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
え、それって
```sh
git merge main
```
したときにしか問題にならなくない？

2022-08-21 15:33 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
> え、それって
> 
> ```shell
> git merge main
> ```
> 
> したときにしか問題にならなくない？

fetch忘れたら同じやで

2022-08-21 15:34 UTC, Shiba-github commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
merge origin/mainはremote見て最新の引っ張ってきてくれるわけではなかったはず
（たぶん）

2022-08-21 15:36 UTC, Actlam commented on src/components/codeArea/cssRenderingArea/CssRenderingArea.tsx
> +            <Text>&emsp;font-size: {fontSize}</Text>
あ、なるほどね
ググったらわかったけどfetch必要っぽい
origin/mainはあくまでリモート追跡ブランチってだけだからその前のfetchを忘れないようにするということで

2022-08-21 17:10 UTC, Shiba-github approved these changes
copy button への追加は他ですでにやってたのね（記憶なし）
![image](https://user-images.githubusercontent.com/30719031/185802778-14f55e8e-96e1-4e45-a492-a9f8793745a0.png)

2022-08-21 17:15 UTC, merged