custom areaにanimationタブを追加
Shiba-github/varia-ui pull request #60
Opened 2022-07-24 17:54 UTC by Shiba-github

close #58

2022-07-24 17:57 UTC, Shiba-github commented
細かなアニメーションや配色は適当に設定

2022-07-26 15:04 UTC, Actlam commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
widthの66vwの根拠が気になる
ここが原因ぽいけど横幅狭くしたときにはみ出してきてるので原因特定と修正お願いします(スクショあり)

2022-07-26 15:05 UTC, Actlam commented
コメントした箇所のSS
![スクリーンショット 2022-07-27 000316](https://user-images.githubusercontent.com/22798833/181041603-65a62de5-182b-4864-8009-f348d18018ce.png)

2022-07-26 15:06 UTC, Actlam requested changes
a

2022-07-26 15:07 UTC, Actlam commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
この辺の66vwが原因っぽいけど横幅狭くしたときにはみ出してます

2022-07-26 15:10 UTC, Shiba-github commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
#31

2022-07-26 15:12 UTC, Shiba-github commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
それとも、これとは全く別件な感じかな？

2022-07-26 15:36 UTC, Actlam commented
@Shiba-github 
テスト

2022-07-26 15:37 UTC, Actlam commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
@Shiba-github 
これmainブランチで検証したんだけど、そっちでは同じ挙動は確認できなかったので別だと思うます

2022-07-26 15:38 UTC, Actlam commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
まぁでも狭いと右側の幅足りなくなる問題もあるのでそこに詰め込んでもよいです

2022-07-26 15:38 UTC, Actlam commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
#31 ?

2022-08-04 15:45 UTC, Shiba-github commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
検証してるけど、こっちだとなんもならぬ…
どうしよっか？

あと、通知来ねぇ

2022-08-13 12:48 UTC, Actlam commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
mainでも起きてたから一旦いすに入れときます

2022-08-13 12:48 UTC, Actlam approved these changes
LGTM

2022-08-13 12:49 UTC, Shiba-github commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
この問題１日つこたけどどうにもならんかった
別のところでもコメント書いたけど、ちょっと大きめの修正説ある

2022-08-13 12:50 UTC, Actlam commented on src/components/cssCustomArea/CssCustomArea.tsx
> +            <Flex bg={'teal.500'} position={'absolute'} width={'66vw'} height={'100vh'} zIndex={animationZIndex}>
かしこまです

2022-08-13 12:55 UTC, merged